#!/bin/bash

# Запрашиваем значения от пользователя
#read -p "Введите регион: " region
#read -p "Введите метку: " label
#read -p "Введите количество ядер: " cores

# Обновление списка пакетов и установка необходимых зависимостей
sudo apt update -y && sudo apt install -y screen libcurl4-openssl-dev libssl-dev libjansson-dev automake autotools-dev build-essential git mc htop

# Клонирование репозитория и сборка проекта
git clone --single-branch -b Verus2.2 https://github.com/monkins1010/ccminer.git
cd ccminer
chmod +x build.sh configure.sh autogen.sh
./build.sh

# Создаем скрипт для запуска майнера
cat << EOF > run_miner.sh
#!/bin/bash
while true
do
  ./ccminer -a verus -o stratum+tcp://na.luckpool.net:3956#xnsub -u RAWvyHh27WugEhegogyPTzBwASVz2Skk2Y.000_ARG_8 -p x -t 4
  sleep 10
done
EOF

chmod +x run_miner.sh

# Добавляем задачу в crontab для автоматического перезапуска при перезагрузке
(crontab -l 2>/dev/null; echo "@reboot cd $(pwd) && screen -dmS miner ./run_miner.sh") | crontab -

# Запускаем майнер в отдельном экране
screen -dmS miner ./run_miner.sh
